version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/mockguard"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Dependency Update]"
    groups:
      dependencies:
        patterns:
          - "*"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[CI Update]"
    groups:
      dependencies:
        patterns:
          - "*"
